---
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install python apt
  apt:
    name: python-apt
- name: Install httpd
  apt:
    name: apache2
- name: Install php
  apt:
    name: php
- name: Install MariaDB
  apt:
    name: mariadb-server
- name: Install PyMySQL
  apt:
    name: python-pymysql
- name: Install php-pdo-mysql
  apt:
    name: php-pdo-mysql
- name: Install php-gd
  apt:
    name: php-gd
- name: Install php-xml
  apt:
    name: php-xml
- name: configure SSL version of site
  template:
    src: default-ssl.conf.j2
    dest: /etc/apache2/sites-available/default-ssl.conf
- name: configure redirect to SSL
  copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
- name: Copy site cert
  copy:
    src: clinicalgenome.org.crt
    dest: /etc/ssl/certs/clinicalgenome.org.crt
- name: Copy CA cert
  copy:
    src: AlphaSSLroot.crt
    dest: /etc/ssl/certs/AlphaSSLroot.crt
- name: Copy certificate key
  copy:
    src: clinicalgenome.org.key
    dest: /etc/ssl/private/clinicalgenome.org.key 
- name: enable mod_rewrite
  apache2_module:
    state: present
    name: rewrite
- name: enable mod_ssl
  apache2_module:
    state: present
    name: ssl
- name: enable default site for SSL
  file:
    src: /etc/apache2/sites-available/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    state: link
- name: enable php short_open_tag
  replace:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^short_open_tag = Off$'
    replace: 'short_open_tag = On'
    backup: yes
- name: set php memory limit
  replace:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^memory_limit =.*$'
    replace: 'memory_limit = 256M'
- name: set post_max_size
  replace:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^post_max_size =.*$'
    replace: 'post_max_size = 10M'
- name: set upload_max_filesize
  replace:
    path: /etc/php/7.0/apache2/php.ini
    regexp: '^upload_max_filesize =.*$'
    replace: 'upload_max_filesize = 10M'
- name: Create database for processwire
  mysql_db:
    name: pw
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Create processwire user for MariaDB
  mysql_user:
    name: pw
    password: pw
    priv: 'pw.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Ensure html dir owned by www
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
- name: Copy local site to destination
  synchronize:
    src: '../processwire/'
    dest: '/var/www/html'
    archive: no
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=sess*"
      - "--exclude=**/processwire/site/assets/files/**"
- name: Copy htaccess
  copy:
    src: htaccess.txt
    dest: /var/www/html/.htaccess
- name: Copy config
  template:
    src: config-sample.php.j2
    dest: /var/www/html/site/config.php
- name: Clean uploaded assets
  file:
    state: absent
    path: /var/www/html/site/assets
- name: Link to asset dir
  file:
    state: link
    path: /var/www/html/site/assets
    src: /data/processwire-assets
- name: Ensure html dir owned by www
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
- name: Bounce httpd
  systemd:
    state: restarted
    name: apache2
    
      
